/**
 * Per-language AST node type definitions for tree-sitter.
 */

/** @typedef {{
 * wasmName?:string,
 * name:string,
 * fileExtensions:string[],
 * classTypes:string[],
 * functionTypes:string[],
 * importTypes:string[],
 * callTypes:string[],
 * variableTypes:string[],
 * nameField:string[],
 * bodyField:string[],
 * callFunctionField:string,
 * callAccessorTypes:string[],
 * callAccessorField:string,
 * callAccessorObjectField:string,
 * modifiersField:string,
 * commentTypes:string[],
 * inheritsTypes:string[],
 * functionLabelParens:boolean
 * }} LanguageConfig
 */

/** @type {Record<string, LanguageConfig>} */
export const LANGUAGES = {
	javascript: {
		name: 'JavaScript',
		fileExtensions: ['js', 'mjs', 'cjs', 'jsx'],
		classTypes: ['class_declaration'],
		functionTypes: ['function_declaration', 'method_definition', 'arrow_function', 'generator_function_declaration'],
		importTypes: ['import_statement', 'import'],
		callTypes: ['call_expression', 'new_expression'],
		variableTypes: ['variable_declaration', 'lexical_declaration'],
		nameField: ['name', 'identifier', 'property_identifier'],
		bodyField: ['body', 'statement_block'],
		callFunctionField: 'function',
		callAccessorTypes: ['member_expression'], callAccessorField: 'property', callAccessorObjectField: 'object',
		modifiersField: '', commentTypes: ['comment', 'html_comment'],
		inheritsTypes: ['class_heritage'], functionLabelParens: true,
	},
	typescript: {
		wasmName: 'tsx',
		name: 'TypeScript',
		fileExtensions: ['ts', 'mts', 'cts', 'tsx'],
		classTypes: ['class_declaration', 'abstract_class_declaration'],
		functionTypes: ['function_declaration', 'method_definition', 'arrow_function', 'generator_function_declaration'],
		importTypes: ['import_statement', 'import'],
		callTypes: ['call_expression', 'new_expression'],
		variableTypes: ['variable_declaration', 'lexical_declaration'],
		nameField: ['name', 'identifier', 'property_identifier', 'type_identifier'],
		bodyField: ['body', 'statement_block'],
		callFunctionField: 'function',
		callAccessorTypes: ['member_expression'], callAccessorField: 'property', callAccessorObjectField: 'object',
		modifiersField: '', commentTypes: ['comment', 'html_comment'],
		inheritsTypes: ['class_heritage', 'implements_clause'], functionLabelParens: true,
	},
	go: {
		name: 'Go',
		fileExtensions: ['go'],
		classTypes: ['type_declaration'],
		functionTypes: ['function_declaration', 'method_declaration'],
		importTypes: ['import_declaration', 'import_spec'],
		callTypes: ['call_expression'],
		variableTypes: ['var_declaration', 'const_declaration', 'short_var_declaration'],
		nameField: ['name', 'identifier', 'type_identifier', 'field_identifier'],
		bodyField: ['body', 'block'],
		callFunctionField: 'function',
		callAccessorTypes: ['selector_expression'], callAccessorField: 'field', callAccessorObjectField: 'operand',
		modifiersField: '', commentTypes: ['comment'],
		inheritsTypes: [], functionLabelParens: true,
	},
	java: {
		name: 'Java',
		fileExtensions: ['java'],
		classTypes: ['class_declaration', 'interface_declaration', 'enum_declaration', 'annotation_type_declaration'],
		functionTypes: ['method_declaration', 'constructor_declaration'],
		importTypes: ['import_declaration'],
		callTypes: ['method_invocation', 'object_creation_expression'],
		variableTypes: ['field_declaration', 'local_variable_declaration'],
		nameField: ['name', 'identifier', 'type_identifier'],
		bodyField: ['body', 'block', 'class_body', 'interface_body', 'enum_body'],
		callFunctionField: 'name',
		callAccessorTypes: ['method_invocation'], callAccessorField: 'name', callAccessorObjectField: 'object',
		modifiersField: 'modifiers', commentTypes: ['comment', 'line_comment', 'block_comment'],
		inheritsTypes: ['superclass', 'super_interfaces'], functionLabelParens: true,
	},
	c: {
		name: 'C',
		fileExtensions: ['c', 'h'],
		classTypes: ['struct_specifier', 'union_specifier', 'enum_specifier'],
		functionTypes: ['function_definition', 'function_declarator'],
		importTypes: ['preproc_include'],
		callTypes: ['call_expression'],
		variableTypes: ['declaration', 'init_declarator'],
		nameField: ['identifier', 'type_identifier'],
		bodyField: ['body', 'compound_statement'],
		callFunctionField: 'function',
		callAccessorTypes: ['field_expression'], callAccessorField: 'field', callAccessorObjectField: 'argument',
		modifiersField: 'type', commentTypes: ['comment'],
		inheritsTypes: [], functionLabelParens: true,
	},
	cpp: {
		name: 'C++',
		fileExtensions: ['cpp', 'cc', 'cxx', 'hpp', 'hh', 'hxx'],
		classTypes: ['class_specifier', 'struct_specifier', 'union_specifier', 'enum_specifier'],
		functionTypes: ['function_definition', 'function_declarator', 'template_declaration'],
		importTypes: ['preproc_include', 'using_declaration'],
		callTypes: ['call_expression', 'new_expression', 'delete_expression'],
		variableTypes: ['declaration', 'init_declarator'],
		nameField: ['identifier', 'type_identifier', 'qualified_identifier'],
		bodyField: ['body', 'compound_statement', 'field_declaration_list'],
		callFunctionField: 'function',
		callAccessorTypes: ['field_expression'], callAccessorField: 'field', callAccessorObjectField: 'argument',
		modifiersField: 'type', commentTypes: ['comment', 'raw_string_literal'],
		inheritsTypes: ['base_class_clause'], functionLabelParens: true,
	},
	c_sharp: {
		name: 'C#',
		fileExtensions: ['cs'],
		classTypes: ['class_declaration', 'struct_declaration', 'interface_declaration', 'enum_declaration', 'record_declaration', 'record_struct_declaration'],
		functionTypes: ['method_declaration', 'constructor_declaration', 'destructor_declaration', 'operator_declaration'],
		importTypes: ['using_directive'],
		callTypes: ['invocation_expression', 'object_creation_expression'],
		variableTypes: ['field_declaration', 'local_declaration_statement', 'property_declaration'],
		nameField: ['name', 'identifier', 'generic_name'],
		bodyField: ['body', 'block', 'arrow_expression_clause'],
		callFunctionField: 'function',
		callAccessorTypes: ['member_access_expression'],
		callAccessorField: 'name',
		callAccessorObjectField: 'expression',
		modifiersField: 'modifiers',
		commentTypes: ['comment', 'documentation_comment'],
		inheritsTypes: ['base_list'],
		functionLabelParens: true,
	},
	css: {
		name: 'CSS',
		fileExtensions: ['css', 'scss', 'less'],
		classTypes: [], functionTypes: [], importTypes: ['import_statement'], callTypes: [], variableTypes: [],
		nameField: ['class_name', 'id_name', 'tag_name'],
		bodyField: ['block'],
		callFunctionField: '', callAccessorTypes: [], callAccessorField: '', callAccessorObjectField: '',
		modifiersField: '', commentTypes: ['comment'],
		inheritsTypes: [], functionLabelParens: false,
	},
	html: {
		name: 'HTML',
		fileExtensions: ['html', 'htm'],
		classTypes: [], functionTypes: [], importTypes: [], callTypes: [], variableTypes: [],
		nameField: ['tag_name', 'attribute_name'],
		bodyField: [],
		callFunctionField: '', callAccessorTypes: [], callAccessorField: '', callAccessorObjectField: '',
		modifiersField: '', commentTypes: ['comment'],
		inheritsTypes: [], functionLabelParens: false,
	},
};

export const SUPPORTED_EXTENSIONS = new Map();
for (const [k, v] of Object.entries(LANGUAGES))
  for (const e of v.fileExtensions)
    SUPPORTED_EXTENSIONS.set(e, k);
